In [ ]:
#!pip install kagglehub
#!pip install --upgrade pip
#!pip install --upgrade requests urllib3 certifi kagglehub
import kagglehub
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

# Download latest version
path = kagglehub.dataset_download("psparks/instacart-market-basket-analysis")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\rudra\.cache\kagglehub\datasets\psparks\instacart-market-basket-analysis\versions\1

In [ ]:
import os

print(os.listdir(path))

['aisles.csv', 'departments.csv', 'orders.csv', 'order_products__prior.csv', 'order_products__train.csv', 'products.csv']

In [ ]:
#!pip install pandas
import pandas as pd

orders = pd.read_csv(path + "/orders.csv")
products = pd.read_csv(path + "/products.csv")
order_products_prior = pd.read_csv(path + "/order_products__prior.csv")
order_products_train = pd.read_csv(path + "/order_products__train.csv")
aisles = pd.read_csv(path + "/aisles.csv")
departments = pd.read_csv(path + "/departments.csv")

In [ ]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [ ]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [ ]:
order_products_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [ ]:
order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [ ]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [ ]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [ ]:
import pandas as pd

order_products = pd.read_csv(path + "/order_products__prior.csv")
products = pd.read_csv(path + "/products.csv")

data = order_products.merge(products, on="product_id")

In [ ]:
data.head(20)

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id
0,2,33120,1,1,Organic Egg Whites,86,16
1,2,28985,2,1,Michigan Organic Kale,83,4
2,2,9327,3,0,Garlic Powder,104,13
3,2,45918,4,1,Coconut Butter,19,13
4,2,30035,5,0,Natural Sweetener,17,13
5,2,17794,6,1,Carrots,83,4
6,2,40141,7,1,Original Unflavored Gelatine Mix,105,13
7,2,1819,8,1,All Natural No Stir Creamy Almond Butter,88,13
8,2,43668,9,0,Classic Blend Cole Slaw,123,4
9,3,33754,1,1,Total 2% with Strawberry Lowfat Greek Strained...,120,16
10,3,24838,2,1,Unsweetened Almondmilk,91,16
11,3,17704,3,1,Lemons,123,4
12,3,21903,4,1,Organic Baby Spinach,123,4
13,3,17668,5,1,Unsweetened Chocolate Almond Breeze Almond Milk,91,16
14,3,46667,6,1,Organic Ginger Root,83,4
15,3,17461,7,1,Air Chilled Organic Boneless Skinless Chicken ...,35,12
16,3,32665,8,1,Organic Ezekiel 49 Bread Cinnamon Raisin,112,3
17,4,46842,1,0,Plain Pre-Sliced Bagels,93,3
18,4,26434,2,1,Honey/Lemon Cough Drops,11,11
19,4,39758,3,1,Chewy 25% Low Sugar Chocolate Chip Granola,3,19

In [ ]:
orders = pd.read_csv(path + "/orders.csv")

data = data.merge(orders, on="order_id")

In [ ]:
data.head(24)

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2,33120,1,1,Organic Egg Whites,86,16,202279,prior,3,5,9,8.0
1,2,28985,2,1,Michigan Organic Kale,83,4,202279,prior,3,5,9,8.0
2,2,9327,3,0,Garlic Powder,104,13,202279,prior,3,5,9,8.0
3,2,45918,4,1,Coconut Butter,19,13,202279,prior,3,5,9,8.0
4,2,30035,5,0,Natural Sweetener,17,13,202279,prior,3,5,9,8.0
5,2,17794,6,1,Carrots,83,4,202279,prior,3,5,9,8.0
6,2,40141,7,1,Original Unflavored Gelatine Mix,105,13,202279,prior,3,5,9,8.0
7,2,1819,8,1,All Natural No Stir Creamy Almond Butter,88,13,202279,prior,3,5,9,8.0
8,2,43668,9,0,Classic Blend Cole Slaw,123,4,202279,prior,3,5,9,8.0
9,3,33754,1,1,Total 2% with Strawberry Lowfat Greek Strained...,120,16,205970,prior,16,5,17,12.0
10,3,24838,2,1,Unsweetened Almondmilk,91,16,205970,prior,16,5,17,12.0
11,3,17704,3,1,Lemons,123,4,205970,prior,16,5,17,12.0
12,3,21903,4,1,Organic Baby Spinach,123,4,205970,prior,16,5,17,12.0
13,3,17668,5,1,Unsweetened Chocolate Almond Breeze Almond Milk,91,16,205970,prior,16,5,17,12.0
14,3,46667,6,1,Organic Ginger Root,83,4,205970,prior,16,5,17,12.0
15,3,17461,7,1,Air Chilled Organic Boneless Skinless Chicken ...,35,12,205970,prior,16,5,17,12.0
16,3,32665,8,1,Organic Ezekiel 49 Bread Cinnamon Raisin,112,3,205970,prior,16,5,17,12.0
17,4,46842,1,0,Plain Pre-Sliced Bagels,93,3,178520,prior,36,1,9,7.0
18,4,26434,2,1,Honey/Lemon Cough Drops,11,11,178520,prior,36,1,9,7.0
19,4,39758,3,1,Chewy 25% Low Sugar Chocolate Chip Granola,3,19,178520,prior,36,1,9,7.0
20,4,27761,4,1,Oats & Chocolate Chewy Bars,48,14,178520,prior,36,1,9,7.0
21,4,10054,5,1,Kellogg's Nutri-Grain Apple Cinnamon Cereal,48,14,178520,prior,36,1,9,7.0
22,4,21351,6,1,Nutri-Grain Soft Baked Strawberry Cereal Break...,48,14,178520,prior,36,1,9,7.0
23,4,22598,7,1,Kellogg's Nutri-Grain Blueberry Cereal,48,14,178520,prior,36,1,9,7.0

In [ ]:
data.isnull().sum()

order_id                        0
product_id                      0
add_to_cart_order               0
reordered                       0
product_name                    0
aisle_id                        0
department_id                   0
user_id                         0
eval_set                        0
order_number                    0
order_dow                       0
order_hour_of_day               0
days_since_prior_order    2078068
dtype: int64

In [ ]:
data.shape

(32434489, 13)

In [ ]:
data.drop_duplicates(subset=['order_id','product_name'], inplace=True)

In [ ]:
data.shape

(32434489, 13)

In [ ]:
data['order_id'] = data['order_id'].astype(str)
data['product_name'] = data['product_name'].astype(str)

In [ ]:
print("Total orders:", data['order_id'].nunique())
print("Total products:", data['product_name'].nunique())

Total orders: 3214874
Total products: 49677

In [ ]:
data['product_name'].value_counts().head(10)

product_name
Banana                    472565
Bag of Organic Bananas    379450
Organic Strawberries      264683
Organic Baby Spinach      241921
Organic Hass Avocado      213584
Organic Avocado           176815
Large Lemon               152657
Strawberries              142951
Limes                     140627
Organic Whole Milk        137905
Name: count, dtype: int64

In [ ]:
#from itertools import combinations
#from collections import Counter

# Example: count pairs in first 1000 orders
#pairs = []
#for order_id, group in data.groupby('order_id'):
 #   products = list(group['product_name'])
  #  pairs += list(combinations(products, 2))

#Counter(pairs).most_common(10)

In [ ]:
top_products = data['product_name'].value_counts().head(100).index
data = data[data['product_name'].isin(top_products)]

In [ ]:
basket = (data
          .groupby(['order_id','product_name'])['product_name']
          .count()
          .unstack()
          .fillna(0)
          .astype('int8'))

In [ ]:
import pandas as pd
# The error occurred because .apply() passes a Series to the lambda, making the boolean check ambiguous.
# We use a vectorized approach instead:
basket = (basket > 0).astype(int)

In [ ]:

basket.head(3)

product_name,100% Raw Coconut Water,100% Whole Wheat Bread,2% Reduced Fat Milk,Apple Honeycrisp Organic,Asparagus,Bag of Organic Bananas,Banana,Bartlett Pears,Blueberries,Boneless Skinless Chicken Breasts,...,Sparkling Natural Mineral Water,Sparkling Water Grapefruit,Spring Water,Strawberries,Uncured Genoa Salami,Unsalted Butter,Unsweetened Almondmilk,Unsweetened Original Almond Breeze Almond Milk,Whole Milk,Yellow Onions
order_id,,,,,,,,,,,,,,,,,,,,,
10,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
100,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
basket = pd.pivot_table(
    data,
    index='order_id',
    columns='product_name',
    aggfunc='size',
    fill_value=0
)

In [ ]:
basket = basket.astype(bool)

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

frequent_itemsets = fpgrowth(
    basket,
    min_support=0.01,
    use_colnames=True
)

In [ ]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric="lift",
    min_threshold=1
)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Banana),(Organic Strawberries),0.200985,0.112572,0.023884,0.118832,1.055615,1.0,0.001258,1.007105,0.065937,0.082450,0.007055,0.165498
1,(Organic Strawberries),(Banana),0.112572,0.200985,0.023884,0.212163,1.055615,1.0,0.001258,1.014188,0.059368,0.082450,0.013989,0.165498
2,(Organic Strawberries),(Bag of Organic Bananas),0.112572,0.161383,0.026211,0.232837,1.442761,1.0,0.008044,1.093141,0.345813,0.105798,0.085205,0.197626
3,(Bag of Organic Bananas),(Organic Strawberries),0.161383,0.112572,0.026211,0.162414,1.442761,1.0,0.008044,1.059507,0.365941,0.105798,0.056165,0.197626
4,(Organic Avocado),(Banana),0.075201,0.200985,0.022709,0.301982,1.502508,1.0,0.007595,1.144691,0.361642,0.089591,0.126402,0.207486

In [ ]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='object')

In [ ]:
rules = rules[
    (rules['confidence'] > 0.4) &
    (rules['lift'] > 1.2) &
    (rules['support'] > 0.01)
]

In [ ]:
print(frequent_itemsets.shape)
frequent_itemsets.head()

(130, 2)

    support                itemsets
0  0.200985                (Banana)
1  0.112572  (Organic Strawberries)
2  0.075201       (Organic Avocado)
3  0.032476   (Organic Half & Half)
4  0.031118         (Yellow Onions)

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

frequent_itemsets = fpgrowth(basket, min_support=0.01, use_colnames=True)
print(frequent_itemsets.head())

    support                itemsets
0  0.200985                (Banana)
1  0.112572  (Organic Strawberries)
2  0.075201       (Organic Avocado)
3  0.032476   (Organic Half & Half)
4  0.031118         (Yellow Onions)

In [ ]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules = rules.sort_values(by="confidence", ascending=False)
rules.head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
28,(Organic Fuji Apple),(Banana),0.038121,0.200985,0.014436,0.378693,1.884181,1.0,0.006774,1.286022,0.487863,0.064255,0.222408,0.225260
27,(Honeycrisp Apple),(Banana),0.033926,0.200985,0.012082,0.356128,1.771911,1.0,0.005263,1.240953,0.450936,0.054221,0.194168,0.208121
24,(Cucumber Kirby),(Banana),0.041389,0.200985,0.013651,0.329826,1.641043,1.0,0.005333,1.192249,0.407497,0.059684,0.161249,0.198873
4,(Organic Avocado),(Banana),0.075201,0.200985,0.022709,0.301982,1.502508,1.0,0.007595,1.144691,0.361642,0.089591,0.126402,0.207486
10,(Seedless Red Grapes),(Banana),0.035168,0.200985,0.010460,0.297428,1.479847,1.0,0.003392,1.137270,0.336074,0.046346,0.120702,0.174736
19,(Organic Raspberries),(Bag of Organic Bananas),0.058291,0.161383,0.017226,0.295519,1.831169,1.0,0.007819,1.190405,0.481997,0.085090,0.159950,0.201130
50,(Organic Hass Avocado),(Bag of Organic Bananas),0.090839,0.161383,0.026514,0.291880,1.808621,1.0,0.011854,1.184287,0.491764,0.117471,0.155610,0.228087
16,(Strawberries),(Banana),0.060798,0.200985,0.017536,0.288434,1.435101,1.0,0.005317,1.122897,0.322812,0.071797,0.109446,0.187843
31,(Apple Honeycrisp Organic),(Bag of Organic Bananas),0.036160,0.161383,0.010078,0.278711,1.727016,1.0,0.004243,1.162664,0.436760,0.053760,0.139906,0.170580
13,(Large Lemon),(Banana),0.064926,0.200985,0.017387,0.267790,1.332385,1.0,0.004337,1.091237,0.266787,0.069959,0.083609,0.177148
23,(Organic Raspberries),(Organic Strawberries),0.058291,0.112572,0.014402,0.247072,2.194801,1.0,0.007840,1.178637,0.578075,0.092050,0.151562,0.187505
39,(Organic Blueberries),(Organic Strawberries),0.042556,0.112572,0.010104,0.237418,2.109035,1.0,0.005313,1.163715,0.549222,0.069668,0.140683,0.163585
2,(Organic Strawberries),(Bag of Organic Bananas),0.112572,0.161383,0.026211,0.232837,1.442761,1.0,0.008044,1.093141,0.345813,0.105798,0.085205,0.197626
40,(Organic Whole Milk),(Banana),0.058652,0.200985,0.013457,0.229441,1.141578,1.0,0.001669,1.036928,0.131747,0.054664,0.035613,0.148198
54,(Limes),(Banana),0.059810,0.200985,0.013513,0.225931,1.124116,1.0,0.001492,1.032227,0.117436,0.054646,0.031220,0.146582
47,(Organic Yellow Onion),(Bag of Organic Bananas),0.048241,0.161383,0.010452,0.216652,1.342473,1.0,0.002666,1.070555,0.268037,0.052475,0.065905,0.140707
36,(Organic Baby Spinach),(Banana),0.102891,0.200985,0.021859,0.212445,1.057019,1.0,0.001179,1.014551,0.060130,0.077508,0.014343,0.160601
1,(Organic Strawberries),(Banana),0.112572,0.200985,0.023884,0.212163,1.055615,1.0,0.001258,1.014188,0.059368,0.082450,0.013989,0.165498
34,(Organic Baby Spinach),(Bag of Organic Bananas),0.102891,0.161383,0.021424,0.208217,1.290203,1.0,0.004819,1.059150,0.250725,0.088217,0.055846,0.170483
56,(Limes),(Large Lemon),0.059810,0.064926,0.011655,0.194863,3.001302,1.0,0.007771,1.161385,0.709230,0.103065,0.138959,0.187185

In [ ]:
rules = rules.sort_values(by="confidence", ascending=False)
rules.head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
28,(Organic Fuji Apple),(Banana),0.038121,0.200985,0.014436,0.378693,1.884181,1.0,0.006774,1.286022,0.487863,0.064255,0.222408,0.225260
27,(Honeycrisp Apple),(Banana),0.033926,0.200985,0.012082,0.356128,1.771911,1.0,0.005263,1.240953,0.450936,0.054221,0.194168,0.208121
24,(Cucumber Kirby),(Banana),0.041389,0.200985,0.013651,0.329826,1.641043,1.0,0.005333,1.192249,0.407497,0.059684,0.161249,0.198873
4,(Organic Avocado),(Banana),0.075201,0.200985,0.022709,0.301982,1.502508,1.0,0.007595,1.144691,0.361642,0.089591,0.126402,0.207486
10,(Seedless Red Grapes),(Banana),0.035168,0.200985,0.010460,0.297428,1.479847,1.0,0.003392,1.137270,0.336074,0.046346,0.120702,0.174736
19,(Organic Raspberries),(Bag of Organic Bananas),0.058291,0.161383,0.017226,0.295519,1.831169,1.0,0.007819,1.190405,0.481997,0.085090,0.159950,0.201130
50,(Organic Hass Avocado),(Bag of Organic Bananas),0.090839,0.161383,0.026514,0.291880,1.808621,1.0,0.011854,1.184287,0.491764,0.117471,0.155610,0.228087
16,(Strawberries),(Banana),0.060798,0.200985,0.017536,0.288434,1.435101,1.0,0.005317,1.122897,0.322812,0.071797,0.109446,0.187843
31,(Apple Honeycrisp Organic),(Bag of Organic Bananas),0.036160,0.161383,0.010078,0.278711,1.727016,1.0,0.004243,1.162664,0.436760,0.053760,0.139906,0.170580
13,(Large Lemon),(Banana),0.064926,0.200985,0.017387,0.267790,1.332385,1.0,0.004337,1.091237,0.266787,0.069959,0.083609,0.177148
23,(Organic Raspberries),(Organic Strawberries),0.058291,0.112572,0.014402,0.247072,2.194801,1.0,0.007840,1.178637,0.578075,0.092050,0.151562,0.187505
39,(Organic Blueberries),(Organic Strawberries),0.042556,0.112572,0.010104,0.237418,2.109035,1.0,0.005313,1.163715,0.549222,0.069668,0.140683,0.163585
2,(Organic Strawberries),(Bag of Organic Bananas),0.112572,0.161383,0.026211,0.232837,1.442761,1.0,0.008044,1.093141,0.345813,0.105798,0.085205,0.197626
40,(Organic Whole Milk),(Banana),0.058652,0.200985,0.013457,0.229441,1.141578,1.0,0.001669,1.036928,0.131747,0.054664,0.035613,0.148198
54,(Limes),(Banana),0.059810,0.200985,0.013513,0.225931,1.124116,1.0,0.001492,1.032227,0.117436,0.054646,0.031220,0.146582
47,(Organic Yellow Onion),(Bag of Organic Bananas),0.048241,0.161383,0.010452,0.216652,1.342473,1.0,0.002666,1.070555,0.268037,0.052475,0.065905,0.140707
36,(Organic Baby Spinach),(Banana),0.102891,0.200985,0.021859,0.212445,1.057019,1.0,0.001179,1.014551,0.060130,0.077508,0.014343,0.160601
1,(Organic Strawberries),(Banana),0.112572,0.200985,0.023884,0.212163,1.055615,1.0,0.001258,1.014188,0.059368,0.082450,0.013989,0.165498
34,(Organic Baby Spinach),(Bag of Organic Bananas),0.102891,0.161383,0.021424,0.208217,1.290203,1.0,0.004819,1.059150,0.250725,0.088217,0.055846,0.170483
56,(Limes),(Large Lemon),0.059810,0.064926,0.011655,0.194863,3.001302,1.0,0.007771,1.161385,0.709230,0.103065,0.138959,0.187185

In [ ]:
rules['antecedents'] = rules['antecedents'].apply(lambda x: ', '.join(list(x)))
rules['consequents'] = rules['consequents'].apply(lambda x: ', '.join(list(x)))

In [ ]:
rules['combo'] = rules['antecedents'] + " + " + rules['consequents']
rules[['combo','confidence','lift']].head(20)

                                                combo  confidence      lift
28                        Organic Fuji Apple + Banana    0.378693  1.884181
27                          Honeycrisp Apple + Banana    0.356128  1.771911
24                            Cucumber Kirby + Banana    0.329826  1.641043
4                            Organic Avocado + Banana    0.301982  1.502508
10                       Seedless Red Grapes + Banana    0.297428  1.479847
19       Organic Raspberries + Bag of Organic Bananas    0.295519  1.831169
50      Organic Hass Avocado + Bag of Organic Bananas    0.291880  1.808621
16                              Strawberries + Banana    0.288434  1.435101
31  Apple Honeycrisp Organic + Bag of Organic Bananas    0.278711  1.727016
13                               Large Lemon + Banana    0.267790  1.332385
23         Organic Raspberries + Organic Strawberries    0.247072  2.194801
39         Organic Blueberries + Organic Strawberries    0.237418  2.109035
2       Organic Strawberries + Bag of Organic Bananas    0.232837  1.442761
40                        Organic Whole Milk + Banana    0.229441  1.141578
54                                     Limes + Banana    0.225931  1.124116
47      Organic Yellow Onion + Bag of Organic Bananas    0.216652  1.342473
36                      Organic Baby Spinach + Banana    0.212445  1.057019
1                       Organic Strawberries + Banana    0.212163  1.055615
34      Organic Baby Spinach + Bag of Organic Bananas    0.208217  1.290203
56                                Limes + Large Lemon    0.194863  3.001302

In [ ]:
top_combos = rules[['combo','confidence','lift']].head(25)
print(top_combos)

                                                combo  confidence      lift
28                        Organic Fuji Apple + Banana    0.378693  1.884181
27                          Honeycrisp Apple + Banana    0.356128  1.771911
24                            Cucumber Kirby + Banana    0.329826  1.641043
4                            Organic Avocado + Banana    0.301982  1.502508
10                       Seedless Red Grapes + Banana    0.297428  1.479847
19       Organic Raspberries + Bag of Organic Bananas    0.295519  1.831169
50      Organic Hass Avocado + Bag of Organic Bananas    0.291880  1.808621
16                              Strawberries + Banana    0.288434  1.435101
31  Apple Honeycrisp Organic + Bag of Organic Bananas    0.278711  1.727016
13                               Large Lemon + Banana    0.267790  1.332385
23         Organic Raspberries + Organic Strawberries    0.247072  2.194801
39         Organic Blueberries + Organic Strawberries    0.237418  2.109035
2       Organic Strawberries + Bag of Organic Bananas    0.232837  1.442761
40                        Organic Whole Milk + Banana    0.229441  1.141578
54                                     Limes + Banana    0.225931  1.124116
47      Organic Yellow Onion + Bag of Organic Bananas    0.216652  1.342473
36                      Organic Baby Spinach + Banana    0.212445  1.057019
1                       Organic Strawberries + Banana    0.212163  1.055615
34      Organic Baby Spinach + Bag of Organic Bananas    0.208217  1.290203
56                                Limes + Large Lemon    0.194863  3.001302
44        Organic Whole Milk + Bag of Organic Bananas    0.192023  1.189862
52        Organic Hass Avocado + Organic Strawberries    0.190997  1.696674
21         Organic Raspberries + Organic Hass Avocado    0.188192  2.071710
57                                Large Lemon + Limes    0.179507  3.001302
8              Organic Avocado + Organic Baby Spinach    0.174697  1.697884

In [ ]:
# Cluster products based on co-occurrence in orders and visualize clusters using Plotly.
# Plotly avoids matplotlib DLL issues in this environment and gives interactive output.
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import pandas as pd

try:
    import plotly.express as px
except ImportError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "plotly"])
    import plotly.express as px

# Transpose the basket so rows are products and columns are orders (binary matrix)
product_matrix = basket.T.astype(float)

# Reduce dimensions for visualization
pca = PCA(n_components=2, random_state=42)
product_2d = pca.fit_transform(product_matrix)

# Choose number of clusters (tune as needed)
n_clusters = 5
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
product_labels = kmeans.fit_predict(product_2d)

# Build a DataFrame for plotting
plot_df = pd.DataFrame({
    'product': product_matrix.index,
    'x': product_2d[:, 0],
    'y': product_2d[:, 1],
    'cluster': product_labels,
})

fig = px.scatter(
    plot_df,
    x='x',
    y='y',
    color='cluster',
    hover_data=['product'],
    title=f'Product clusters (KMeans k={n_clusters})',
    labels={'x': 'PCA 1', 'y': 'PCA 2'},
)
fig.update_traces(marker=dict(size=10, opacity=0.75))
fig.show()

# Print example products per cluster
for c in sorted(plot_df['cluster'].unique()):
    sample = plot_df[plot_df['cluster'] == c]['product'].head(10).tolist()
    print(f"\nCluster {c} sample products ({len(sample)} shown):")
    print(sample)

Cluster 0 sample products (10 shown):
['100% Raw Coconut Water', '100% Whole Wheat Bread', '2% Reduced Fat Milk', 'Asparagus', 'Bartlett Pears', 'Blueberries', 'Boneless Skinless Chicken Breasts', 'Broccoli Crown', 'Bunched Cilantro', 'Carrots']

Cluster 1 sample products (1 shown):
['Banana']

Cluster 2 sample products (1 shown):
['Bag of Organic Bananas']

Cluster 3 sample products (3 shown):
['Organic Baby Spinach', 'Organic Hass Avocado', 'Organic Strawberries']

Cluster 4 sample products (10 shown):
['Apple Honeycrisp Organic', 'Cucumber Kirby', 'Honeycrisp Apple', 'Large Lemon', 'Limes', 'Organic Avocado', 'Organic Blueberries', 'Organic Cucumber', 'Organic Fuji Apple', 'Organic Gala Apples']

In [ ]:
# Optionally visualize cluster centers (in PCA space)
centers = kmeans.cluster_centers_
centers_df = pd.DataFrame(centers, columns=['x', 'y'])
centers_df['cluster'] = range(len(centers_df))

fig = px.scatter(
    plot_df,
    x='x',
    y='y',
    color='cluster',
    hover_data=['product'],
    title=f'Product clusters + centers (k={n_clusters})',
    labels={'x': 'PCA 1', 'y': 'PCA 2'},
)
fig.add_scatter(
    x=centers_df['x'],
    y=centers_df['y'],
    mode='markers+text',
    marker=dict(size=18, symbol='x', color='black'),
    text=centers_df['cluster'],
    textposition='top center',
    name='centers',
)
fig.show()

In [ ]:
# Save trained clustering model + PCA transformer + product index so a web app can load and use it.
import pickle

model_artifact = {
    "kmeans": kmeans,
    "pca": pca,
    # Needed to map web-input product names to the expected feature order
    "product_index": list(product_matrix.index),
    "n_clusters": n_clusters,
}

with open("product_cluster_model.pkl", "wb") as f:
    pickle.dump(model_artifact, f)

print("Saved product_cluster_model.pkl (contains kmeans+pca+product_index)")

Saved product_cluster_model.pkl (contains kmeans+pca+product_index)